apiVersion: apps/v1
kind: Deployment
metadata:
  name: apikubernets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apikubernets
  template:
    metadata:
      labels:
        app: apikubernets
    spec:
      containers:
      - name: apikubernets
        image: apikubernets:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apikubernets-service
spec:
  type: NodePort
  selector:
    app: apikubernets
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
